### ISSUE TITLE
Modifier keys

### ISSUE THREAD

**Issue by Steampunkery** [thebracket/rltk_rs#10]
How do I go about accessing what modifier keys are pressed? I'm looking to detect the ">" keypress, so I assumed I need to detect simultaneous "." and shift presses. I followed the examples using `VirtualKeyCode` and traced the code back to the `winit` library which has a `ModifiersState` struct which appears to be what I'm looking for, but I'm not sure how to access it from an `Rltk` context.

Thanks!

**Comment by dagit** [comment]
I noticed that `VirtualKeycode` has entries for modifier keys. Does it work if you check for [`LShift`](https://github.com/thebracket/rltk_rs/blob/master/src/platform_specific.rs#L739) and `.`?

Sorry I'm not able to test that suggestion at the moment.

**Comment by Steampunkery** [comment]
I don't think you can test for two enum variants at the same time because it can only be one variant at a time.

**Comment by thebracket** [comment]
Sorry for the delay, I'm moving house and don't have Internet at the new home yet. I'll hopefully have access Mon/Tue, and will get to this. `VirtualKeyCode` does support modifiers, but I'm handling them pretty badly right now - especially on the boundary with `wasm`. So I'll see what I can do to make a usable API for all platforms.
Thanks for letting me know!

**Comment by thebracket** [comment]
I just merged code to add support for checking `shift`, `control` and `alt` status when polling keyboard events, and added example 16 to demonstrate it.
