### ISSUE TITLE
"index out of bounds" error while running dwarf_map example

### ISSUE THREAD

**Issue by vmedea** [thebracket/rltk_rs#11]
i can't reliably reproduce it, but it seems to happen when the mouse cursor is out of the window:
```
thread 'main' panicked at 'index out of bounds: the len is 512000 but the index is 512727', /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2715:10
stack backtrace: 
.
  11: <usize as core::slice::SliceIndex<[T]>>::index                                                      
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2715             
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index                                      
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2566            
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index                                          
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/vec.rs:1791                 
  14: <ex14_dwarfmap::State as rltk::GameState>::tick
             at examples/ex14-dwarfmap.rs:217
  15: rltk::platform_specific::tock
             at ./src/platform_specific.rs:209
…
```
OS: linux, rustc `rustc 1.38.0`

**Comment by thebracket** [comment]
Thanks for the report, and sorry for the delay - I've been moving house, and the new house doesn't have Internet yet. I think I know what's happening there (you sometimes get some odd mouse events when the mouse moves out of bounds), and it should be solvable by adding some clamping to the mouse handler.
It'll probably be Mon/Tue before I can get to it - but I'll make it a priority. Thanks!

**Comment by thebracket** [comment]
I just committed a possible fix for this. I couldn't get it to crash on my system, after this change (which clamps mouse input to the coordinates of the active terminal).
I've started pondering a better fix overall that will help with a few issues people have run into, involving keeping track of *actual* canvas size after a window resize event (Linux in particular likes to adjust the window boundaries when it adds decorations, causing a few issues with the window size not matching what we asked for)

**Comment by vmedea** [comment]
Thanks ! The fix makes a lot of sense, and I haven't managed to run into this issue anymore after this, so I think we can conclude this is solved :smile:. The dwarf_map window is not resizable on Linux so I couldn't try that.
