### ISSUE TITLE
PNG Tiles

### ISSUE THREAD

**Issue by chrisburnor** [thebracket/rltk_rs#12]
I took the default `example_tiles.jpg` and converted to `example_tiles.png`.  Doing so, does require adding the 'png_codec' feature in `Cargo.toml`.  It runs fine, but the output is all messed up. 

This is the 07 tile example with a png spritesheet:
<img width="626" alt="Screen Shot 2019-09-29 at 9 16 30 AM" src="https://user-images.githubusercontent.com/200679/65835436-e537ef80-e29a-11e9-9a45-69d9f322bf29.png">

I'm on OSX 10.14.6 (18G95).  So this might be related to mac drivers too.

**Comment by thebracket** [comment]
Sorry for the delay, I've been moving house! I don't have a Mac to test on, but I think I remember running into this (it's actually why I ended up using JPG). I'll see if I can get to it on Monday or Tuesday when I have Internet at the new house (and hopefully fewer boxes), and try to get PNG support working properly.
There are some issues with different formats of PNG, laying out memory differently. In this case, it looks like the library is providing one format and RLTK is happily assuming that the layout is another.

**Comment by thebracket** [comment]
I've merged a commit that has it successfully loading and displaying PNG (instead of JPG) files in both webasm and Windows on my test system. Any luck there?

**Comment by thebracket** [comment]
It's working on a couple of fresh installs (Linux VM) with just PNGs now, so I believe this issue is resolved.
