### ISSUE TITLE
Tiles rendering repeating

### ISSUE THREAD

**Issue by Stenodyon** [thebracket/rltk_rs#24]
Hello,

I am experiencing a rendering bug with tiles (native, not wasm) where tiles seem to render repeated instead of scaling properly:
![image](https://user-images.githubusercontent.com/15184100/69447382-aed89700-0d56-11ea-911f-da90c6e14982.png)

The rendering is working properly for me up until efee85c5ad09e2ac3b5d183884a40f6ac7b5a18f. The next commit, 9306f2c5baa958eb0ce7319ba3732ee8577b2a34, just gives me a black screen. 48a997ebacb876c6108c49626e6ad4b6bed80488 and forward gives me this bug.

**System:**
Manjaro Linux 4.19.84
NVIDIA GeForce GTX 850M, drivers: 4.6.0 NVIDIA 430.64

**Comment by thebracket** [comment]
Yikes! That's definitely a problem. I'll see what I can do to get that fixed ASAP.

**Comment by thebracket** [comment]
Ok, I can replicate the problem in my virtual Linux. It's a re-hash of the resizing problems I ran into earlier, but now much more widespread. It works so long as your window is *exactly* the expected size (which happens on Windows, but Linux resizes when the controls appear) - but scaling is utterly trashed by a resize.

I'll probably revert the native rendering path to before those patches, while I figure out how to work around this.
