### ISSUE TITLE
Resource path initialization unclear

### ISSUE THREAD

**Issue by zaszi** [thebracket/rltk_rs#30]
I initialize a context as follows:

```
let mut ctx = Rltk::init_simple8x8(
    WIDTH,
    HEIGHT,
    "mygame",
    "resources",
);
```

As far as I tell, the last parameter is expanded to ./resources/terminal8x8.png, and is required to initialize a context using the terminal8x8.png font included in the resources directory. However, if I move terminal8x8.png to ./data instead of ./resources and change that parameter accordingly, my application panics. Even stranger, if I completely remove the resources directory and do a full recompile, my application still works as expected.

Panic message:
```
thread 'main' panicked at 'Failed to load texture: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1165:5
```

What am I not understanding here?

**Comment by thebracket** [comment]
I need to work on this a bit. Right now, there's a bit of a mismatch between "embedding" resources (the file gets embedded at compile time) and simply accessing them - and the library doesn't always make it clear what's actually happening. I believe there's a hidden bit (that shouldn't be hidden) that is catching `resources/terminal8x8` and going for an embedded version.

I'll try and get this cleaned up in the next version. Thanks!

**Comment by thebracket** [comment]
I'm hoping that this has been mitigated by the recent `initialization` branch. If you don't specify a resources folder, then it uses embedded content (the built-in terminal fonts and anything you embed via the macros). If you do, it looks on the filesystem first.

**Comment by CGMossa** [comment]
I'm also having this issue while reading the Hands-on Book. 

My version says:
```
thread 'main' panicked at 'Failed to load texture: IoError(Os { code: 2, kind: NotFound, message: "The system cannot find the file 
specified." })', C:\Users\[]\.cargo\registry\src\github.com-1ecc6299db9ec823\bracket-terminal-0.8.2\src\hal\gl_common\font.rs:41:18
```
