### ISSUE TITLE
rltk builds fail on Windows, Linux

### ISSUE THREAD

**Issue by ysgard** [thebracket/rltk_rs#31]
I'm going through the Rusty Roguelike  and I'm up to chapter 1.7 - coding on the Mac didn't offer any problems, but when I tried to compile the project on either Linux or Windows (using the latest nightly build) I run into the same problem with each:

```
error[E0609]: no field `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> C:\Users\ysgar\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.22.0-alpha4\src\api\egl\mod.rs:694:17
    |
694 |         if !egl.SwapBuffersWithDamageKHR.is_loaded() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `0`

error[E0599]: no method named `SwapBuffersWithDamageKHR` found for type `&api::egl::egl::Egl` in the current scope
   --> C:\Users\ysgar\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.22.0-alpha4\src\api\egl\mod.rs:714:17
    |
714 |             egl.SwapBuffersWithDamageKHR(
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&api::egl::egl::Egl`

error[E0609]: no field `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> C:\Users\ysgar\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.22.0-alpha4\src\api\egl\mod.rs:740:13
    |
740 |         egl.SwapBuffersWithDamageKHR.is_loaded()
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `0`

error: aborting due to 3 previous errors
```

This seems like it might be a problem with `glutin-0.22.0-alpha4`?  I tried with both `rltk 0.5.9` (recommended by the tutorial) and the latest, `rltk 0.5.12`.

**Comment by ysgard** [comment]
Should I punt this upstream? Can rltk work with the last stable release of glutin, 0.21.0?

**Comment by thebracket** [comment]
I have it building on Windows with `0.22.0-alpha3`, and it builds fine. I haven't tried any other versions recently. I'll give it a go during the week. Thanks for letting me know!

**Comment by ysgard** [comment]
Looks like glutin moved to `0.22.0-alpha5` over the weekend, and with that, the error (at least on linux, haven't checked windows yet) has gone away.  Going to chalk this one to living on the cutting edge and closing it. Thanks for the quick response!
