### ISSUE TITLE
Error compiling 'Hello World' example: NoAvailablePixelFormat on Mac OS

### ISSUE THREAD

**Issue by amedviediev** [thebracket/rltk_rs#32]
I am currently on rltk = "0.5.12" on Mac Os and I'm still experiencing this issue. Full stacktrace:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:933
  16: rltk::hal::native::init::init_raw
             at /Users/amedvedev/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/hal/native/init.rs:20
  17: rltk::rltk::Rltk::init_raw
             at /Users/amedvedev/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/rltk.rs:42
  18: rltk::rltk::Rltk::init_simple8x8
             at /Users/amedvedev/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/rltk.rs:53
  19: rust_rogue_tutorial::main
             at src/main.rs:39
  20: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  24: std::panicking::try
             at src/libstd/panicking.rs:271
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  28: rust_rogue_tutorial::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101

_Originally posted by @amedviediev in https://github.com/thebracket/rltk_rs/issues/17#issuecomment-567111218_

**Comment by thebracket** [comment]
Oh no, this one came back. There's a difficulty with different video cards getting Glutin to pick a screen mode that the video card agrees to render. I'll fire up my virtual Mac tomorrow and see if I can find a working combination.
Do you get the same problem with `cargo run --example ex01-helloworld --no-default-features --features amethyst-metal``?

**Comment by amedviediev** [comment]
This doesn't compile, but if I remove line 74 from cargo.toml (required-features = [ "opengl" ]) this one does:
cargo run --example ex01-helloworld --no-default-features --features amethyst_engine_metal

However, the example still doesn't run, it now gives the following error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "No physical devices found" }', src/libcore/result.rs:1165:5

**Comment by amedviediev** [comment]
I have a Intel HD Graphics 3000 512 MB on this Mac if that helps

**Comment by amedviediev** [comment]
Upon some tinkering with init.rs I've discovered that it also works if I disable hardware acceleration or change gl from a specific version to glutin::GlRequest::Latest

**Comment by janhrastnik** [comment]
I'm experiencing the same issue when running the hello world example. I'm on arch, wayland, with intel UHD Graphics 620. Here's the backtrace:

   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: rltk::hal::native::init::init_raw
             at ./src/hal/native/init.rs:18
  17: rltk::rltk::Rltk::init_raw
             at ./src/rltk.rs:42
  18: rltk::rltk::Rltk::init_simple8x8
             at ./src/rltk.rs:53
  19: ex01_helloworld::main
             at examples/ex01-helloworld.rs:91
  20: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  24: std::panicking::try
             at src/libstd/panicking.rs:265
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  27: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by janhrastnik** [comment]
Changing my terminal from terminator to alacritty has fixed this issue for me.

**Comment by thebracket** [comment]
I'll close this for now, then. Pixel formats are a recurring issue, I'll keep looking for a better way!
