### ISSUE TITLE
error[E0599]: no variant or associated item named `EventsCleared` found for type `winit::event::Event<_>` in the current scope

### ISSUE THREAD

**Issue by brianbruggeman** [thebracket/rltk_rs#36]
Basic steps are:

`cargo new rl`
`cd rl`
`echo 'rltk = "*"' >> Cargo.toml`
`cargo build`

We compile fine until we hit `rltk` at which point, I have the error.

This happens in both mac and windows (haven't had a chance to try in Linux yet).

Also, I tried compiling and building a simple winit app by itself and had no issues there.

What am I missing?

**Comment by brianbruggeman** [comment]
Ooops!  Thanks!

**Comment by thebracket** [comment]
I'm pretty sure that this is the same problem as #35 - basically `winit` changed their interface on me overnight, and broke a few things. In turn, this seems to have rippled down and caused issues for Glutin and possibly Amethyst! I'll be investigating it as fast as I can, and trying to get it fixed. I *thought* I had it pinned to working versions.

Thanks for letting me know. I'd try locking RLTK to version `0.5.13` and see if that helps; apparently the latest version has a few issues. :-(

**Comment by brianbruggeman** [comment]
I went back 0.5.13, .12, .11...

Looks like they may all be pulling in the latest winit (0.20.0-alpha?).

**Comment by thebracket** [comment]
They are. I'll have 0.5.15 published in the next few minutes, I have it running locally now. Sorry for the inconvenience!

**Comment by thebracket** [comment]
RLTK version 0.5.15 is now live on cargo/crates. It fixes the issue for me.

**Comment by brianbruggeman** [comment]
Success!  Thank you!
