### ISSUE TITLE
License file names Google as Copyright holder

### ISSUE THREAD

**Issue by kikito** [thebracket/rltk_rs#4]
In case this was a typo, your license file says:

```
Copyright (c) 2010-2019 Google, Inc. http://angularjs.org
```

You probably want to replace `Google, Inc` with your name, or the name of your company.

Incidentally, the  `http://angularjs.org` link does not conform to [the MIT template](https://opensource.org/licenses/MIT) (there should be no link)

**Comment by thebracket** [comment]
Wow, that's what I get for copy-pasting from another project. Thanks! I'll get that fixed shortly.
