### ISSUE TITLE
On macOS, using a high resolution monitor like the built-in screen, text rendering is incorrect

### ISSUE THREAD

**Issue by vtbassmatt** [thebracket/rltk_rs#46]
On my Mac (which has a non-high-DPI monitor attached), if I run an rltk app from a terminal on the laptop screen, I get super-tiny font rendering in the wrong place. If I drag the terminal over to the external monitor and then launch the app, everything looks fine.

Laptop screen:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/714283/72293781-31c4f200-3622-11ea-89c5-d20f213387c5.png">

External monitor:
![image](https://user-images.githubusercontent.com/714283/72293802-3ee1e100-3622-11ea-8b7d-7155ac2d5258.png)

The code is chapter 1 of the book:
```rust
rltk::add_wasm_support!();
use rltk::{Rltk, GameState, Console};

struct State {}
impl GameState for State {
    fn tick(&mut self, ctx : &mut Rltk) {
        ctx.cls();
        ctx.print(1, 1, "Hello Rust World!");
    }
}

fn main() {
    let context = Rltk::init_simple8x8(80, 50, "Hello Rust World", "resources");
    let gs = State{ };
    rltk::main_loop(context, gs);
}
```

**Comment by cpv** [comment]
I'm having the same issue. Additionally if I resize the window on my laptop screen the rendering corrects itself.

**Comment by vtbassmatt** [comment]
Actually, now I'm trying it with no monitor attached, and I still get the incorrect rendering on the laptop screen. Updating title.

Like @cpv it fixes the rendering if I tweak the size of the window.

**Comment by ronaldlens** [comment]
I have the same issue, Rltk 0.5.17, Macbook Pro. On the laptop screen (retina) the text renders to the bottom left 25% of the window:

<img width="752" alt="Screenshot 2020-01-14 at 22 16 00" src="https://user-images.githubusercontent.com/2178191/72383413-b6476b80-371b-11ea-9532-6174395f34c6.png">

Same as @cpv, tweak the size of the window and it's fixed. Same regardless of whether an external monitor is attached or not. After tweaking the size:

<img width="761" alt="Screenshot 2020-01-14 at 22 19 24" src="https://user-images.githubusercontent.com/2178191/72383543-fc9cca80-371b-11ea-9ad9-9a740ee0a0ff.png">

**Comment by Revii** [comment]
Same on windows laptop with 4K screen (build-in). After resize everything looks good.
