### ISSUE TITLE
find_highest_exit, in djiskra, work backward

### ISSUE THREAD

**Issue by Elliosson** [thebracket/rltk_rs#68]
The entity go on target instead of fleeing.
In the #[cfg(not(feature = "threaded"))], a and b seem to be in the bad order.
But the #[cfg(feature = "threaded")] version it seem to be ok.

**Comment by vojta7** [comment]
#69, I already opened a pull request for it.

**Comment by thebracket** [comment]
I just merged the PR, it looks fixed now. Thanks everyone!
