### ISSUE TITLE
Input does not work on Linux

### ISSUE THREAD

**Issue by mgedmin** [thebracket/rltk_rs#7]
I'm trying to run the examples from https://github.com/thebracket/rustrogueliketutorial on Ubuntu 19.04, in a Wayland session, using rustc 1.37.0.

Most of the time all keyboard and mouse input gets ignored: I cannot move the little @ arround, and I cannot close the window by clicking the X button in the window title.

Input worked during my initial testing (but some of the events were dropped), when my system was busy compiling Firefox in the background, so I think this is due to some kind of race condition?

I've looked at the output of WAYLAND_DEBUG=1 cargo run and failed to find any keyboard/mouse events, just a tight loop of screen updates.  But then I've never used WAYLAND_DEBUG before and I don't even know what the events are supposed to look like.

**Comment by mgedmin** [comment]
I can reproduce the problem with `cargo run --example ex03-walking` in rltk_rs.

I cannot reproduce the problem with `cargo run --example window` in glutin.

If I add a debug print to the rltk_rs main_loop, I see these events only:

```
NewEvents(Init)
WindowEvent { window_id: WindowId(Wayland(WindowId(93895232124464))), event: RedrawRequested }
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
NewEvents(Poll)
EventsCleared
...
```
```

**Comment by mgedmin** [comment]
If I change

```
        *control_flow = ControlFlow::Poll;
```
to
```
        *control_flow = ControlFlow::Wait;
```
inside main_loop, things start working just fine.  My debug print shows a bunch of repeating events like

```
EventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 361448, tv_nsec: 987016680 }, requested_resume: None })
EventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 361449, tv_nsec: 3515879 }, requested_resume: None })
EventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 361449, tv_nsec: 20400787 }, requested_resume: None })
EventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 361449, tv_nsec: 36947381 }, requested_resume: None })
```

when I'm not touching the mouse/keyboard, indicating that the Wait isn't actually blocking the main loop.  (Also, `cargo run --example ex01-helloworld` shows the animation animating smoothly.)

Now today is the first time I learned a thing called `glutin` exists, so I'm not the best person to suggest fixes, but maybe use ControlFlow::Wait?

**Comment by thebracket** [comment]
Nice find! I just tried it, and it's *odd*. It zooms along if the mouse is in the window, and pauses completely when the mouse leaves. I'm not sure that's a bad thing! I'll try and research a bit more.

**Comment by vks** [comment]
This fixes it for me as well, at the cost of much higher CPU usage.

**Comment by thebracket** [comment]
I'll close this for now, and keep looking for a better way.
