### ISSUE TITLE
Very high CPU use

### ISSUE THREAD

**Issue by hammerandtongs** [thebracket/rltk_rs#70]
In working through Roguelike Tutorial in Rust on Linux (chapter 08 so far, thanks again for the great work) I've had very high (100%) cpu utilization even "idle" on both an AMD GPU workstation and Intel GPU laptop.

Memory is quite reasonable at 30MB still.

In trying some of the demos in rltk I found them also to have the same behavior even with curses (curses14-dwarfmap) as the backend.

Is this expected behavior?

The rltk tick as I understand it is 60 per second but given how little it should be doing this seems like high utilization?

**Comment by thebracket** [comment]
I believe this is because `winit` is polling, and the main loop winds up running as fast as it can. It seems more reasonable on other platforms. I'll see if I can tame the beast a bit.

**Comment by hammerandtongs** [comment]
Hmmm well a timely*cough* blog post -

https://joetsoi.github.io/fix-your-timestep-rust-ggez/

Using the "vsync" demo from his repository which uses ggez and .... the same version of winit 0.19.5 as you and amethyst are.

I get stable 60 and 4-5% utilization (--release) on both intel and amd.

Also wondering if you want to support ssh(I think you mentioned that in passing somewhere) won't you lose vsync as a clock with no graphics context?

**Comment by thebracket** [comment]
Wow, thanks for that! I'll see what I can do to improve matters.

**Comment by thebracket** [comment]
Yes: if you use one of the terminal back-ends, then vsync doesn't exist anymore (and neither do various other options).

Interestingly, I just tried putting an `std::thread::yield_now()` in the main loop - and (on my Ubuntu VM in VirtualBox) CPU usage actually went *up* according to `top`. There's something very odd going on there.

**Comment by thebracket** [comment]
I've put the first steps of optional frame-rate limitation, with `thread::sleep` calls into the branch https://github.com/thebracket/rltk_rs/tree/issue_70_highcpu

It's implemented for native, crossterm and curses. The timing isn't quite right yet, but it does mitigate CPU time on both my Windows box and Linux VM.

**Comment by hammerandtongs** [comment]
Felt pretty good on the Intel laptop 4-5% --release.

I'll try to poke around a bit more later this evening or tomorrow on the AMD, but thank you for sorting this out!

**Comment by hammerandtongs** [comment]
So my problems on AMD seem sorted as well.

However -

`cargo build --release --example curses14-dwarfmap --features curses --no-default-features`

Still has very high cpu but I suspect I'm not getting the "crossterm" bits pulled in?
