### ISSUE TITLE
tick() not called consisently on windows 10

### ISSUE THREAD

**Issue by dagit** [thebracket/rltk_rs#9]
I've noticed some weird behavior with `tick()` on windows. You can see it with the the first example. If the mouse is over the window, everything works as you would expect and FPS counter shows 120 (on a 120hz display). If I move the mouse away from the window, so that it's no longer over the client area of the window, then when I stop moving the mouse you can see the game basically freeze. If you wait a second and move the mouse again then it starts processing `tick()` again. The FPS counter will then update and you can make it go arbitrarily low by waiting between when you move the mouse. I can post a video clip if that explanation is confusing.

I looked through the issue tracker for glutin and I didn't see any issues like this so I suspect the bug is in the Rltk code. I tried the example on linux (X11) and it behaved as I would have expected (full frame rate all the time, regardless of mouse movement or position).

Looking at the Rltk event loop, it looks like `tick()` is called after all the events have been cleared and the application is about to give control back to the OS. The only thing I can think is that perhaps on windows glutin only creates this `EventsCleared` event when there were events to process and that on linux this event is created more often.

Have you noticed this bug before? It's probably not a big deal for turn based simulations. I think for simulations that are not turn based that the current API might be restrictive in the sense that `tick()` appears to be tied to the framerate. (Unless I'm missing something, of course.) For instance, is it possible to have a simulation that runs at 20hz with animations and event  processing that runs at 60hz?

**Comment by vks** [comment]
This might be related to #6.

**Comment by dagit** [comment]
> 
> 
> This might be related to #6.

After reading through #6, I think you actually meant #7. Anyway, I tried changing it to `Poll` instead of `Wait` and now it behaves as I would expect.

**Comment by thebracket** [comment]
Sorry for the delay - moving house is crazy, and I don't have reliable Internet at home until early next week. I'm pretty sure this is related to the Linux polling problems. `*control_flow = ControlFlow::Wait;` gets events on Linux, but on Windows 10 it only works if the mouse is inside the window (so there are events being streamed in). On Windows 10, `*control_flow = ControlFlow::Poll;` works consistently, but gives some problems for Linux users. I'll see if I can find a better way, otherwise it might be time for some platform-specific code.

Thanks!

**Comment by thebracket** [comment]
I've added a commit varying the tick behavior between Linux (which doesn't seem to like polling on a lot of platforms, there are earlier bugs about this) and Windows (which doesn't tick unless the window has focus and the mouse is over it on Wait mode). Hopefully that'll help.

**Comment by thebracket** [comment]
I've merged in some more changes that have it running smoothly on both Windows 10 and Ubuntu (in a VM on VirtualBox) on my machine.

**Comment by dagit** [comment]
Thanks! Much appreciated.
